好的，我们继续深入讲解下一部分内容：**NumPy基础**。

---

### 1.2 NumPy基础

NumPy（Numerical Python）是Python中用于科学计算的基础库。它提供了高效的多维数组对象以及各种用于操作数组的函数。NumPy是大多数数据处理和机器学习库的基础，了解并熟练使用NumPy是数据处理的关键。

#### NumPy数组

NumPy的核心是其强大的N维数组对象`ndarray`，它可以存储和操作大规模的数据集。以下是一些常用的NumPy数组操作：

##### 创建数组

1. 从列表创建数组：

In [2]:
import numpy as np

# 从列表创建一维数组
array1 = np.array([1, 2, 3, 4, 5])

# 从列表创建二维数组
array2 = np.array([[1, 2, 3], [4, 5, 6]])

print(array1)
print(array2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


2. 使用NumPy内置函数创建数组：

In [ ]:
# 创建全零数组
zeros = np.zeros((3, 4))

# 创建全一数组
ones = np.ones((2, 3))

# 创建单位矩阵
eye = np.eye(4)

# 创建随机数组
random_array = np.random.random((3, 3))

print(zeros)
print(ones)
print(eye)
print(random_array)

##### 数组操作

1. 数组切片和索引：

In [4]:
# 创建一个5x5的数组
array = np.arange(25).reshape(5, 5)

# 访问数组元素
print(array[2, 3])  # 输出第3行第4列的元素

# 数组切片
print(array[1:4, 1:4])  # 输出子数组

13
[[ 6  7  8]
 [11 12 13]
 [16 17 18]]


2. 数组运算：

In [5]:
# 数组加法
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result = array1 + array2

# 数组乘法
result = array1 * array2

# 数组广播
array3 = np.array([[1, 2, 3], [4, 5, 6]])
result = array3 + array1

print(result)

[[2 4 6]
 [5 7 9]]


3. 常见的数组函数：

In [6]:
# 求数组的最大值、最小值和平均值
print(array.max())
print(array.min())
print(array.mean())

# 数组求和和累积和
print(array.sum())
print(array.cumsum())

# 数组转置
print(array.T)

24
0
12.0
300
[  0   1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153
 171 190 210 231 253 276 300]
[[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]


##### 示例代码

In [7]:
import numpy as np

# 创建一个5x5的数组
array = np.arange(25).reshape(5, 5)
print("原始数组:")
print(array)

# 访问数组元素
element = array[2, 3]
print("\n第3行第4列的元素:", element)

# 数组切片
sub_array = array[1:4, 1:4]
print("\n子数组:")
print(sub_array)

# 数组加法
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result_add = array1 + array2
print("\n数组加法结果:")
print(result_add)

# 数组乘法
result_mul = array1 * array2
print("\n数组乘法结果:")
print(result_mul)

# 数组广播
array3 = np.array([[1, 2, 3], [4, 5, 6]])
result_broadcast = array3 + array1
print("\n数组广播结果:")
print(result_broadcast)

# 求数组的最大值、最小值和平均值
max_val = array.max()
min_val = array.min()
mean_val = array.mean()
print("\n数组的最大值:", max_val)
print("数组的最小值:", min_val)
print("数组的平均值:", mean_val)

# 数组求和和累积和
sum_val = array.sum()
cumsum_val = array.cumsum()
print("\n数组的求和:", sum_val)
print("数组的累积和:")
print(cumsum_val)

# 数组转置
transpose_array = array.T
print("\n数组的转置:")
print(transpose_array)

原始数组:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

第3行第4列的元素: 13

子数组:
[[ 6  7  8]
 [11 12 13]
 [16 17 18]]

数组加法结果:
[5 7 9]

数组乘法结果:
[ 4 10 18]

数组广播结果:
[[2 4 6]
 [5 7 9]]

数组的最大值: 24
数组的最小值: 0
数组的平均值: 12.0

数组的求和: 300
数组的累积和:
[  0   1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153
 171 190 210 231 253 276 300]

数组的转置:
[[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]


这些是NumPy库的一些基础操作和方法。在数据处理过程中，NumPy可以极大地提高计算效率和代码的简洁性。